spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/bookstore
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      idle-timeout: 10000
    tomcat:
      max-active: 100
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: postgresql
  security:
    jwt:
      token:
        secret-key: jwtapp
        expire-length: 3600000
